name: Python Application Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3

    - name: 1. Creating virtual env
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 2. Installing dependencies
      run: |
        pip install -r requirements.txt

    - name: 3. Downloading model 
      run: | 
        pip install gdown
        gdown https://drive.google.com/uc?id=1ZYG8HQw-HJW4Wba4RbD_9n3vmqDQ5onn

    - name: 4. Run Evaluation
      run: |
        cd Q3/
        chmod +x eval.cpython-310-x86_64-linux-gnu.so
        python eval.py --token a91aae52cff9ef65932db06b150ffd47
